#include "archimedes/acmTexture.h"

#include "archimedes/acmBuffer.h"
#include "archimedes/acmDevice.h"
#include "archimedes/acmVkConvert.h"
#include "archimedes/acmVkMemory.h"
#include "archimedes/acmVkOneShot.h"

#include <vulkan/vulkan.h>

#include <algorithm>
#include <cassert>

namespace
{
	// Depth(-stencil) formats need a different usage + view aspect than color, so the
	// Texture picks them by format: a depth format makes a depth attachment, anything
	// else a sampleable/copyable color attachment.
	bool isDepthFormat(acm::Format format)
	{
		return format == acm::Format::D32_Sfloat || format == acm::Format::D24_Unorm_S8_Uint;
	}

	// Full mip chain count for the extent: floor(log2(max(w,h))) + 1.
	uint32_t computeMipLevels(acm::Extent2D extent)
	{
		uint32_t levels = 1;
		uint32_t dim = std::max(extent.width, extent.height);
		while (dim > 1)
		{
			dim >>= 1;
			++levels;
		}
		return levels;
	}

	// One image-memory barrier over a mip-level range, the boilerplate the upload path
	// repeats for the layout/stage transitions around the copy + mip blits.
	void transition(VkCommandBuffer cb, VkImage image, uint32_t baseMip, uint32_t levelCount,
					VkImageLayout oldLayout, VkImageLayout newLayout, VkAccessFlags srcAccess, VkAccessFlags dstAccess,
					VkPipelineStageFlags srcStage, VkPipelineStageFlags dstStage)
	{
		VkImageMemoryBarrier barrier = {};
		barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
		barrier.oldLayout = oldLayout;
		barrier.newLayout = newLayout;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image = image;
		barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
		barrier.subresourceRange.baseMipLevel = baseMip;
		barrier.subresourceRange.levelCount = levelCount;
		barrier.subresourceRange.layerCount = 1;
		barrier.srcAccessMask = srcAccess;
		barrier.dstAccessMask = dstAccess;
		vkCmdPipelineBarrier(cb, srcStage, dstStage, 0, 0, nullptr, 0, nullptr, 1, &barrier);
	}
} // namespace

struct acm::Texture::impl
{
	acm::Device device;
	acm::Format format{acm::Format::Undefined};
	acm::Extent2D extent;
	uint32_t mipLevels{1};
	VkImage image{VK_NULL_HANDLE};
	acm::Allocation allocation; // sub-range of a pooled block
	VkImageView imageView{VK_NULL_HANDLE};

	~impl()
	{
		if (!device.valid())
			return;

		// Defer onto the device's frame-fenced queue; enqueue order is run order, so
		// view -> image -> free the memory range last. The allocator outlives the
		// graveyard flush, so capture a raw pointer to it (not the Device handle).
		VkDevice dev = device.vkDevice();
		if (imageView)
		{
			VkImageView iv = imageView;
			device.enqueueDestroy([dev, iv]
								  { vkDestroyImageView(dev, iv, nullptr); });
		}
		if (image)
		{
			VkImage img = image;
			device.enqueueDestroy([dev, img]
								  { vkDestroyImage(dev, img, nullptr); });
		}
		if (allocation.valid())
		{
			auto* alloc = &device.memoryAllocator();
			acm::Allocation a = allocation;
			device.enqueueDestroy([alloc, a]
								  { alloc->free(a); });
		}
	}
};

acm::Texture::Texture(acm::Device device, acm::Format format, acm::Extent2D extent, bool mipmapped, bool storage)
	: m()
{
	auto impl = std::make_shared<acm::Texture::impl>();
	impl->device = device;
	impl->format = format;
	impl->extent = extent;

	const VkFormat vkFormat = acm::toVk(format);
	const bool depth = isDepthFormat(format);
	const VkImageAspectFlags aspect = depth ? VK_IMAGE_ASPECT_DEPTH_BIT : VK_IMAGE_ASPECT_COLOR_BIT;
	// Mips are a color, upload-path concern (generated by blitting); depth/attachment
	// textures stay single-level.
	impl->mipLevels = (mipmapped && !depth) ? computeMipLevels(extent) : 1;

	VkImageCreateInfo imageInfo = {};
	imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	imageInfo.imageType = VK_IMAGE_TYPE_2D;
	imageInfo.format = vkFormat;
	imageInfo.extent = {extent.width, extent.height, 1};
	imageInfo.mipLevels = impl->mipLevels;
	imageInfo.arrayLayers = 1;
	imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
	imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
	imageInfo.usage = depth ? VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
							: (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT);
	if (storage && !depth)
		imageInfo.usage |= VK_IMAGE_USAGE_STORAGE_BIT; // a compute shader can write it
	imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

	if (vkCreateImage(impl->device.vkDevice(), &imageInfo, nullptr, &impl->image) != VK_SUCCESS)
	{
		m_error = acm::Error("failed to create image");
		return;
	}

	VkMemoryRequirements memReq;
	vkGetImageMemoryRequirements(impl->device.vkDevice(), impl->image, &memReq);
	impl->allocation = impl->device.memoryAllocator().allocate(memReq, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
	if (!impl->allocation.valid())
	{
		m_error = acm::Error("failed to allocate texture memory");
		return;
	}
	vkBindImageMemory(impl->device.vkDevice(), impl->image, impl->allocation.memory, impl->allocation.offset);

	VkImageViewCreateInfo viewInfo = {};
	viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
	viewInfo.image = impl->image;
	viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
	viewInfo.format = vkFormat;
	viewInfo.subresourceRange.aspectMask = aspect;
	viewInfo.subresourceRange.baseMipLevel = 0;
	viewInfo.subresourceRange.levelCount = impl->mipLevels;
	viewInfo.subresourceRange.baseArrayLayer = 0;
	viewInfo.subresourceRange.layerCount = 1;
	if (vkCreateImageView(impl->device.vkDevice(), &viewInfo, nullptr, &impl->imageView) != VK_SUCCESS)
	{
		m_error = acm::Error("failed to create texture image view");
		return;
	}

	m = impl;
}

acm::Error acm::Texture::upload(const void* pixels, size_t size)
{
	assert(!isDepthFormat(m->format) && "acm::Texture::upload: depth textures cannot be uploaded");

	// Mip generation blits down with a linear filter, which needs the format to be a
	// linear-filterable sampled image. If it isn't, fall back to a single level.
	uint32_t mipLevels = m->mipLevels;
	if (mipLevels > 1)
	{
		VkFormatProperties fp;
		vkGetPhysicalDeviceFormatProperties(m->device.getGPU().device, acm::toVk(m->format), &fp);
		if (!(fp.optimalTilingFeatures & VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT))
			mipLevels = 1;
	}

	acm::Buffer staging = m->device.createBuffer(size, acm::BufferUsage::Staging);
	if (!staging.valid())
		return acm::Error("Texture::upload: failed to create staging buffer");
	if (auto err = staging.write(pixels, size))
		return err;

	VkImage image = m->image;
	const acm::Extent2D extent = m->extent;
	return acm::oneShotSubmit(m->device, [&staging, image, extent, mipLevels](VkCommandBuffer cb)
							   {
		// All levels UNDEFINED -> TRANSFER_DST, then fill level 0 from the staging buffer.
		transition(cb, image, 0, mipLevels, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
				   0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);

		VkBufferImageCopy region = {};
		region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
		region.imageSubresource.layerCount = 1;
		region.imageExtent = {extent.width, extent.height, 1};
		vkCmdCopyBufferToImage(cb, staging.vkBuffer(), image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

		// Generate each mip by blitting (linear, halving) from the level above, moving
		// each finished source level to SHADER_READ_ONLY as we go.
		int32_t mw = int32_t(extent.width);
		int32_t mh = int32_t(extent.height);
		for (uint32_t i = 1; i < mipLevels; ++i)
		{
			transition(cb, image, i - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
					   VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);

			const int32_t nw = mw > 1 ? mw / 2 : 1;
			const int32_t nh = mh > 1 ? mh / 2 : 1;
			VkImageBlit blit = {};
			blit.srcOffsets[1] = {mw, mh, 1};
			blit.srcSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
			blit.srcSubresource.mipLevel = i - 1;
			blit.srcSubresource.layerCount = 1;
			blit.dstOffsets[1] = {nw, nh, 1};
			blit.dstSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
			blit.dstSubresource.mipLevel = i;
			blit.dstSubresource.layerCount = 1;
			vkCmdBlitImage(cb, image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, VK_FILTER_LINEAR);

			transition(cb, image, i - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
					   VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
			mw = nw;
			mh = nh;
		}

		// The last level is still TRANSFER_DST (it was never a blit source): finish it.
		transition(cb, image, mipLevels - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
				   VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT); });
}

acm::Format acm::Texture::format() const
{
	return m->format;
}

acm::Extent2D acm::Texture::getExtent() const
{
	return m->extent;
}

uint32_t acm::Texture::mipLevels() const
{
	return m->mipLevels;
}

VkImage acm::Texture::vkImage() const
{
	return m->image;
}

VkImageView acm::Texture::vkImageView() const
{
	return m->imageView;
}
